/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2022-12-31 10:22:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class navbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	html,\r\n");
      out.write("body {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("	width: 100vw;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	font-family: \"Roboto\", sans-serif;\r\n");
      out.write("	background-image: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("	margin: 20px 0;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-wrapper {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	flex-direction: row;\r\n");
      out.write("	flex-wrap: nowrap;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	width: 90%;\r\n");
      out.write("	height: 80px;\r\n");
      out.write("	border-radius: 0 0 15px 15px;\r\n");
      out.write("	padding: 0 25px;\r\n");
      out.write("	z-index: 2;\r\n");
      out.write("	background: #fff;\r\n");
      out.write("	box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-tabs {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-tab:not(:last-child) {\r\n");
      out.write("	padding: 10px 25px;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	border-right: 1px solid #eee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-tab:last-child {\r\n");
      out.write("	padding: 10px 0 0 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-tab,\r\n");
      out.write(".menu-btn {\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hidden {\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 800px) {\r\n");
      out.write("	.nav-container {\r\n");
      out.write("		position: fixed;\r\n");
      out.write("		display: none;\r\n");
      out.write("		overflow-y: auto;\r\n");
      out.write("		z-index: -1;\r\n");
      out.write("		top: 0;\r\n");
      out.write("		right: 0;\r\n");
      out.write("		width: 280px;\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		background: #fff;\r\n");
      out.write("		box-shadow: -1px 0 2px rgba(0, 0, 0, 0.2);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.nav-tabs {\r\n");
      out.write("		flex-direction: column;\r\n");
      out.write("		align-items: flex-end;\r\n");
      out.write("		margin-top: 80px;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.nav-tab:not(:last-child) {\r\n");
      out.write("		padding: 20px 25px;\r\n");
      out.write("		margin: 0;\r\n");
      out.write("		border-right: unset;\r\n");
      out.write("		border-bottom: 1px solid #f5f5f5;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.nav-tab:last-child {\r\n");
      out.write("		padding: 15px 25px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.menu-btn {\r\n");
      out.write("		position: relative;\r\n");
      out.write("		display: block;\r\n");
      out.write("		margin: 0;\r\n");
      out.write("		width: 20px;\r\n");
      out.write("		height: 15px;\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("		z-index: 2;\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("		border-radius: 10px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.menu-btn .menu {\r\n");
      out.write("		display: block;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 2px;\r\n");
      out.write("		border-radius: 2px;\r\n");
      out.write("		background: #111;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.menu-btn .menu:nth-child(2) {\r\n");
      out.write("		margin-top: 4px;\r\n");
      out.write("		opacity: 1;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.menu-btn .menu:nth-child(3) {\r\n");
      out.write("		margin-top: 4px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#menuToggle:checked + .menu-btn .menu {\r\n");
      out.write("		transition: transform 0.2s ease;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#menuToggle:checked + .menu-btn .menu:nth-child(1) {\r\n");
      out.write("		transform: translate3d(0, 6px, 0) rotate(45deg);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#menuToggle:checked + .menu-btn .menu:nth-child(2) {\r\n");
      out.write("		transform: rotate(-45deg) translate3d(-5.71429px, -6px, 0);\r\n");
      out.write("		opacity: 0;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#menuToggle:checked + .menu-btn .menu:nth-child(3) {\r\n");
      out.write("		transform: translate3d(0, -6px, 0) rotate(-45deg);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#menuToggle:checked ~ .nav-container {\r\n");
      out.write("		z-index: 1;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		animation: menu-slide-left 0.3s ease;\r\n");
      out.write("	}\r\n");
      out.write("	@keyframes menu-slide-left {\r\n");
      out.write("		0% {\r\n");
      out.write("			transform: translateX(200px);\r\n");
      out.write("		}\r\n");
      out.write("		to {\r\n");
      out.write("			transform: translateX(0);\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("        <div class=\"nav-wrapper\">\r\n");
      out.write("            <nav>\r\n");
      out.write("                <div class=\"nav-container\">\r\n");
      out.write("                    <ul class=\"nav-tabs\">\r\n");
      out.write("                        <li class=\"nav-tab\"> <a href=\"./home\">Home</a></li>\r\n");
      out.write("                        <li class=\"nav-tab\"> <a href=\"./search\">Search</a></li>\r\n");
      out.write("                        <li class=\"nav-tab\"> <a href=\"./add\">Add</a></li>\r\n");
      out.write("                        <li class=\"nav-tab\"> <a href=\"./remove\">Remove</a></li>\r\n");
      out.write("                        <li class=\"nav-tab\"> <a href=\"./update\">update</a></li>\r\n");
      out.write("                        <li class=\"nav-tab\"> <a href=\"./logout\">logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
