package com.jspiders.servlets.netflix;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


@WebServlet("/homepage")
public class NetFlix extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    public NetFlix() {
        super();
        // TODO Auto-generated constructor stub
    }

	
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doPost(request, response);
		
		
	}

	
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		response.setContentType("text/html");
		PrintWriter printWriter = response.getWriter();
		printWriter.println("<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\">\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"UTF-8\">\r\n"
				+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "    <title>Netflix India - Watch TV Shows Online, Watch Movies Online</title>\r\n"
				+ "    <style>\r\n"
				+ "        *{\r\n"
				+ "    padding: 0;\r\n"
				+ "    margin: 0;\r\n"
				+ "    box-sizing: border-box;\r\n"
				+ "}\r\n"
				+ "body{\r\n"
				+ "    width: 100%;\r\n"
				+ "    height: 100%;\r\n"
				+ "    color: white;\r\n"
				+ "    background: black;\r\n"
				+ "    font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif;\r\n"
				+ "}\r\n"
				+ ".container::before{\r\n"
				+ "    content: \"\";\r\n"
				+ "    background: url(images/netflix-bg.jpg) no-repeat center center/cover;\r\n"
				+ "    position: absolute;\r\n"
				+ "    height: 100%;\r\n"
				+ "    width: 100%;\r\n"
				+ "    opacity: 0.3;\r\n"
				+ "    z-index: -1;\r\n"
				+ "}\r\n"
				+ ".container .navbar{\r\n"
				+ "    height: 100px;\r\n"
				+ "    display: flex;\r\n"
				+ "}\r\n"
				+ ".container .navbar .left{\r\n"
				+ "    background-image: url('https://miro.medium.com/max/828/1*5lyavS59mazOFnb55Z6znQ.webp');\r\n"
				+ "    height: 100vh;\r\n"
				+ "    width: 100vw;\r\n"
				+ "    background-repeat: no-repeat;\r\n"
				+ "    background-size: cover;\r\n"
				+ "\r\n"
				+ "    display: flex;\r\n"
				+ "    float: left;\r\n"
				+ "}\r\n"
				+ "/* .container .navbar .left img{\r\n"
				+ "    height: 100px;\r\n"
				+ "    position: absolute;\r\n"
				+ "    left: 35px;\r\n"
				+ "} */\r\n"
				+ ".container .navbar .right{\r\n"
				+ "    display: flex;\r\n"
				+ "    height: 100px;\r\n"
				+ "    float: right;\r\n"
				+ "    position: absolute;\r\n"
				+ "    right: 50px;\r\n"
				+ "}\r\n"
				+ ".container .navbar .right .language{\r\n"
				+ "    margin: auto;\r\n"
				+ "    align-items: center;\r\n"
				+ "    justify-content: center;\r\n"
				+ "    font-size: 18px;\r\n"
				+ "    padding: 7px 10px;\r\n"
				+ "    color: white;\r\n"
				+ "    background: none;\r\n"
				+ "    cursor: pointer;\r\n"
				+ "    margin-right: 15px;\r\n"
				+ "}\r\n"
				+ ".container .navbar .right .language option{\r\n"
				+ "    background-color: grey;\r\n"
				+ "}\r\n"
				+ ".container .navbar .right button{\r\n"
				+ "    margin: auto;\r\n"
				+ "    align-items: center;\r\n"
				+ "    justify-content: center;\r\n"
				+ "    font-size: 18px;\r\n"
				+ "    font-weight: 400;\r\n"
				+ "    padding: 7px 17px;\r\n"
				+ "    background: #e50914;\r\n"
				+ "    cursor: pointer;\r\n"
				+ "    outline: none;\r\n"
				+ "    border-radius: 4px;\r\n"
				+ "    border: none;\r\n"
				+ "}\r\n"
				+ ".container .navbar .right button a{\r\n"
				+ "    text-decoration: none;\r\n"
				+ "    color: white;\r\n"
				+ "}\r\n"
				+ ".container .title{\r\n"
				+ "    padding: 70px 45px;\r\n"
				+ "}\r\n"
				+ ".container .title .content{\r\n"
				+ "    width: 950px;\r\n"
				+ "    margin: auto;\r\n"
				+ "    padding: 75px 0;\r\n"
				+ "    text-align: center;\r\n"
				+ "}\r\n"
				+ ".container .title .content h1{\r\n"
				+ "    width: 650px;\r\n"
				+ "    margin: auto;\r\n"
				+ "    font-size: 3.1rem;\r\n"
				+ "    text-align: center;\r\n"
				+ "}\r\n"
				+ ".container .title .content h2{\r\n"
				+ "    width: 650px;\r\n"
				+ "    margin: auto;\r\n"
				+ "    font-size: 1.6rem;\r\n"
				+ "    text-align: center;\r\n"
				+ "}\r\n"
				+ ".container .title .content form h3{\r\n"
				+ "    font-size: 1rem;\r\n"
				+ "    margin: 18px 0;\r\n"
				+ "    text-align: center;\r\n"
				+ "}\r\n"
				+ ".container .title .content form .email{\r\n"
				+ "    width: 1000px;\r\n"
				+ "    margin: auto;\r\n"
				+ "}\r\n"
				+ ".container .title .content form .email input{\r\n"
				+ "    height: 60px;\r\n"
				+ "    width: 450px;\r\n"
				+ "    margin: auto;\r\n"
				+ "    padding: 20px;\r\n"
				+ "    font-size: 20px;\r\n"
				+ "    outline: none;\r\n"
				+ "}\r\n"
				+ ".container .title .content form .email button{\r\n"
				+ "    margin: auto;\r\n"
				+ "    height: 60px;\r\n"
				+ "    width: 180px;\r\n"
				+ "    align-items: center;\r\n"
				+ "    justify-content: center;\r\n"
				+ "    font-size: 20px;\r\n"
				+ "    padding: 7px 17px;\r\n"
				+ "    background: #e50914;\r\n"
				+ "    cursor: pointer;\r\n"
				+ "    outline: none;\r\n"
				+ "    border-top-right-radius: 2px;\r\n"
				+ "    border-bottom-right-radius: 2px;\r\n"
				+ "    border: none;\r\n"
				+ "    margin-left: -5px;\r\n"
				+ "}\r\n"
				+ ".container .title .content form .email button:hover{\r\n"
				+ "    background-color: #f40612;\r\n"
				+ "}\r\n"
				+ ".container .title .content form .email button a{\r\n"
				+ "    text-decoration: none;\r\n"
				+ "    color: white;\r\n"
				+ "}\r\n"
				+ "    </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "\r\n"
				+ "    <div class=\"container\">\r\n"
				+ "        <nav class=\"navbar\">\r\n"
				+ "            <div class=\"left\">\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"right\">\r\n"
				+ "                <select name=\"language\" class=\"language\">\r\n"
				+ "                    <option value=\"English\">English</option>\r\n"
				+ "                    <option value=\"Hindi\">Hindi</option>\r\n"
				+ "                </select>\r\n"
				+ "                <button><a href=\"#\">Sign In</a></button>\r\n"
				+ "            </div>\r\n"
				+ "        </nav>\r\n"
				+ "\r\n"
				+ "        <div class=\"title\">\r\n"
				+ "            <div class=\"content\">\r\n"
				+ "                <h1>Unlimited movies, TV shows and more.</h1>\r\n"
				+ "                <h2>Watch anywhere. Cancel anytime.</h2>\r\n"
				+ "                <form action=\"#\">\r\n"
				+ "                    <h3>Ready to watch? Enter your email to create or restart your membership.</h3>\r\n"
				+ "                    <div class=\"email\">\r\n"
				+ "                        <input type=\"email\" name=\"email\" placeholder=\"Email address\">\r\n"
				+ "                        <button><a href=\"#\">Get Started  ></a></button>\r\n"
				+ "                    </div>\r\n"
				+ "                </form>\r\n"
				+ "            </div>\r\n"
				+ "        </div>\r\n"
				+ "    </div>\r\n"
				+ "</body>\r\n"
				+ "</html>");
		
	}

}
